### ISSUE TITLE
你好,无法启动项目,是我的使用方式有误?

### ISSUE THREAD

**Issue by binary1997** [tencentyun/iotexplorer-h5-freepanels#3]
npm run dev -- --category=FiveRoadLight --panel=panel-default

> iotexplorer-h5-freepanels@1.0.0 dev E:\code\iotexplorer-h5-freepanels-main
> npx webpack serve --config webpack/webpack.config.js --mode=development --watch "--category=FiveRoadLight" "--panel=panel-default"

[webpack-cli] Error: Unknown option '--watch'
[webpack-cli] Run 'webpack --help' to see available commands and options
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! iotexplorer-h5-freepanels@1.0.0 dev: `npx webpack serve --config webpack/webpack.config.js --mode=development --watch "--category=FiveRoadLight" "--panel=panel-default"`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the iotexplorer-h5-freepanels@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\LM-PC\AppData\Roaming\npm-cache\_logs\2021-03-11T06_27_09_637Z-debug.log

**Comment by noonhorse** [comment]
@binary1997

**Comment by noonhorse** [comment]
Closes #3
