### ISSUE TITLE
按照文档运行:npm run dev -- --category=FiveRoadLight --panel=panel-default ,不能编译

### ISSUE THREAD

**Issue by zp0605** [tencentyun/iotexplorer-h5-freepanels#5]
npm run dev -- --category=FiveRoadLight --panel=panel-default

> iotexplorer-h5-freepanels@1.0.0 dev /Users/belon/Documents/GitHub/iotexplorer-h5-freepanels
> npx webpack serve --config webpack/webpack.config.js --mode=development --watch "--category=FiveRoadLight" "--panel=panel-default"

error: unknown option '--category=FiveRoadLight'
[webpack-cli] Run 'webpack --help' to see available commands and options
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! iotexplorer-h5-freepanels@1.0.0 dev: `npx webpack serve --config webpack/webpack.config.js --mode=development --watch "--category=FiveRoadLight" "--panel=panel-default"`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the iotexplorer-h5-freepanels@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

**Comment by imgss** [comment]
文档是`npm run dev --category=FiveRoadLight --panel=panel-default`，你多了个`--`
